### ISSUE TITLE
Compatibility with v4?

### ISSUE THREAD

**Issue by josbol** [dark-loop/functions-authorize#10]
Hi!

We have been using your attribute on azure functions v3 without issue but when testing on an azure functions project v4 (.NET 6), we immediatly get an 401 error and the following error in the console:

[2022-11-04T18:51:15.280Z] Executed 'Registrar_Lead' (Failed, Id=69f566b5-f755-45c7-92cf-c951c3974f26, Duration=668ms)
[2022-11-04T18:51:15.281Z] System.Private.CoreLib: Exception while executing function: Registrar_Lead. Microsoft.AspNetCore.Server.Kestrel.Core: StatusCode cannot be set because the response has already started.

Any idea what this might cause?

Kinds regards!

**Comment by artmasa** [comment]
Are you using Isolated or Hosted mode? I have tested in hosted mode without issues. But I think it would not work well with Isolated mode.

**Comment by artmasa** [comment]
Do you think you might have another filter trying to write to the response on the `HttpContext` after the authorization filter has changed the status code?
If you are receiving a 401 with a `[FunctionAuthorize]` decorated  and `Anonymous` HttpTrigger function. it means the Authorization extension is doing it's job, but something else is trying to change the response status again.

**Comment by josbol** [comment]
We are getting this error even when running locally, so I don't think it's
a matter running in isolated mode or not, but I'll double check everything
to see if there's something odd going in the rest of the Startup code.

**Comment by artmasa** [comment]
Have created #11 PR adding a v4 sample project

**Comment by artmasa** [comment]
@josbol, can you send me a list of your public dependencies with some public startup initialization and see if I can reproduce the problem on my side?

**Comment by artmasa** [comment]
@josbol, I was able to reproduce your error. It was happening when not checking for an already changed response and then executing the default challenge and forbid authorization framework calls. I'm about to merge a PR to fix it. I will produce a new 3.1.2 preview package you might want to try soon and confirm it solves your problem.

**Comment by artmasa** [comment]
The PR closed the issue. Reopening to wait for your response for confirmation on fixed issue.

**Comment by artmasa** [comment]
Closing issue as it has been resolved with #14
