### ISSUE TITLE
Configuration["AzureAD:Instance"]

### ISSUE THREAD

**Issue by mmajcica** [dark-loop/functions-authorize#17]
Hi,

in your examples you are passing some parameters from your local config file. I am curios what the value should we supply for one particular of those, "AzureAD:Instance". What precisely is expected to be supplied for the Instance value?

Thanks

**Comment by artmasa** [comment]
@mmajcica, this would be the host used for authentication. In my examples the assumption is that I'm using AAD and using `AzureAD:Instance` and `AzureAD:TenantId` to compose the `Authority` property for the JWT options. Commonly Authority refers to the IdP URL you are using. This can be AAD, AAD B2C, Okta, Google

**Comment by artmasa** [comment]
@mmajcica, were you able to successfully setup your JWT configuration?

**Comment by artmasa** [comment]
I will go ahead and close this issue for now. Feel free to reach out if you are still in need of assistance.

**Comment by artmasa** [comment]
Configuring JWT is not really part of my framework, but of ASP.NET Core.
Here is an example of a question using the same calls to ASP.NET's `AuthenticationBuilder` I use in the examples: https://stackoverflow.com/questions/66891211/net-core-api-jwt-token-validation

The question on stackoverflow above is not related to Azure Functions in any way.

The basic idea is that we have 3 basic components in our configuration:
- `AzureAD:ApiIdUrl` > This is the audience in the token. This settings is called `ResourceId` or `Audience`
- `AzureAD:Instance` > This is the IdP endpoint in your case points to `https://login.onmicrosoft.com/`
- `AzureAD:TenantId` > This is the tenant that the tokens are expected to be targeting. The audience is also expected to be registered under this tenant.

`JWTBearerOptions` has 2 properties to configure, among others, Audience and Authority. Audience in AAD will point to your App registration and Authority will be in this case the concatenation of the AAD endpoint (Instance) and the tenant as this is how AAD routes the authentication requests. (https://login.onmicrosoft.com/<your-tenant-id>)

Hope this helps
