### ISSUE TITLE
401 Exception: Bearer was not authenticated. Failure message: IDX10231: Audience validation failed. Delegate returned false

### ISSUE THREAD

**Issue by BenjaminWang1031** [dark-loop/functions-authorize#19]
Using Azure AD to secure an Azure Function Http Trigger, everything works locally, but get 401 when gets deployed to Azure.
 
StartUp.cs:

```
            builder
                    .AddAuthentication(options =>
                    {
                        options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                        options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                    })
                    .AddJwtBearer(jwtOptions =>
                    {
                        jwtOptions.Authority = "https://login.microsoftonline.com/xxx.com";
                        jwtOptions.Audience = "https://xxx.com/app-id-uri";
                        jwtOptions.RequireHttpsMetadata = false;
                    });
```

And I could see the "aud": "https://xxx.com/app-id-uri" in the access_token generated, they match.

However, when I use postman to hit the deployed azure function, it returns 401, works locally though.
```
[Verbose]   AuthenticationScheme: ArmToken was not authenticated.
[Information]  Failed to validate the token.
[Information]   Bearer was not authenticated. Failure message: IDX10231: Audience validation failed. Delegate returned false, securitytoken: ....
```
Any advise would be appreciated!

**Comment by artmasa** [comment]
Hi @BenjaminWang1031

How have you structured your HTTP function? Can you provide an example?
Are you also using App Service Auth (EasyAuth)?

**Comment by BenjaminWang1031** [comment]
@artmasa 

I am not using EasyAuth.

Example: It's a GraphQL endpoint with http trigger, I enabled role check there, which works locally as well, the role is included in the access token.
```
    public class MyHandler
    {
        [FunctionAuthorize(Roles = "myRole")]
        [FunctionName("MyHttpFunction")]
        public Task<IActionResult> MyFunction(
       [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = "graphql/{**slug}")] HttpRequest request, [GraphQL] IMyExecutor executor)
       => executor.ExecuteAsync(request);
    }
```

**Comment by artmasa** [comment]
@BenjaminWang1031, were you able to overcome this problem?

I would recommend removing any existing bearer configuration from Azure Functions.
In the `AddJwtBearer` overload there is an extra `removeBuiltInConfig` parameter you can use to force JWT configuration to be reset.

```C#
    .AddJwtBearer(options => { ... }, removeBuiltInConfig: true);
```
Any prior options configuration done by the Functions SDK is removed from services.

**Comment by BenjaminWang1031** [comment]
@artmasa That magic line worked!! Thank you.

I also have a sort of request: To allow disabling authorization without removing `[FunctionAuthorize] `attribute, unless there's an easy way to add that attribute dynamically at runtime. This is for local development, as well as disabling in prod environment with a simple config change if needed.

**Comment by artmasa** [comment]
@BenjaminWang1031 glad to hear that worked.

I will look into your suggestion. Go ahead and file a new issue and I will try to research a solution.

Thanks!

**Comment by artmasa** [comment]
Closing as it has been resolved
