### ISSUE TITLE
Add support for disabling authorization without removing the [FunctionAuthorize] attribute

### ISSUE THREAD

**Issue by BenjaminWang1031** [dark-loop/functions-authorize#20]
In order to disable authentication & authorization easily for local development, as well as production when needed with just a simple configuration(appsetting) change, so that no code change + redeployment is required. Please help research a way to allow disabling authorization without removing the `[FunctionAuthorize] `attribute, or if we can add that attribute dynamically at runtime. 

Original discussion: https://github.com/dark-loop/functions-authorize/issues/19#issuecomment-1908990656

Thanks!

**Comment by artmasa** [comment]
What kind of scenarios are we trying to support in production? I'm a little concerned that a simple configuration that can be leaked into production may affect applications desired behavior.
My idea was to mix configuration plus code like in ASP.NET `env.IsDevelopment()` can ensure the conditions are right to disable auth.

**Comment by BenjaminWang1031** [comment]
@artmasa The scenario would be when someone messed up with the role/scope settings and caused a lot of authorization failures, or the authorization server is down or overwhelming, or the auth implementation prod go-live does not work out as expected, or other cases when we need to disable the authorization check temporarily, there should be an option to turn it off easily with a configuration change. 

Even with `env.IsDevelopment()` check, it is still not possible to add or remove the `[FunctionAuthorize]` attribute at runtime, unless the package itself exposes certain property or method for it.

**Comment by artmasa** [comment]
@BenjaminWang1031, I have created #22 for this suggestion

**Comment by artmasa** [comment]
Hi @BenjaminWang1031, I have created a preview for 3.1.3: https://www.nuget.org/packages/DarkLoop.Azure.Functions.Authorize/3.1.3-preview-240211-5
I have validated on my side the expected behavior, any chance you can take a look on your side. Based on feedback I'm looking into promoting to release in the next days

**Comment by BenjaminWang1031** [comment]
Thanks for releasing the preview! @artmasa 
It worked as expected, I was able to disable the authorization at the app level without removing the `[FunctionAuthorize]` attribute!

**Comment by artmasa** [comment]
Awesome! Thanks for the feedback @BenjaminWang1031 
I will be promoting to release later today or tomorrow

**Comment by artmasa** [comment]
I will go ahead and close this issue as the implementation is contained in 3.1.3 release package
