### ISSUE TITLE
Question: what is the purpose of having custom Authentication logic right before another Authentication done by Policy Evaluator

### ISSUE THREAD

**Issue by nazar-kuzo** [dark-loop/functions-authorize#3]
Hey,
Thanks for the library, that is a bi relief for those who suffer from Azure Functions limitations 😉

I`m investigating issue with Authentication request happening twice and I know that this is problem sitting rather on my end but I noticed that `FunctionsAuthorizeFilter` has Authentication routing happening twice:

1. `AuthenticateRequestAsync()` in line 63
2. `evaluator.AuthenticateAsync(effectivePolicy, context.HttpContext)` in line 65

Could you please explain the purpose for such logic?

https://github.com/dark-loop/functions-authorize/blob/e8a4f45ece7e1526123f06de2d105c679e20b080/src/DarkLoop.Azure.Functions.Authorize/Filters/FunctionsAuthorizeFilter.cs#L63-L65

**Comment by artmasa** [comment]
great catch. I'm updating the class to integrate the configured `AuthenticationSchemes` for the application in the `IAuthorizeData` items passed to the filter.
The method call in line 63 will disappear. I will let you know when updated.

**Comment by nazar-kuzo** [comment]
many thanks! your library is a 🔥🔥🔥 BTW, you might be interested in reading this issue [https://github.com/Azure/azure-functions-host/issues/6805](https://github.com/Azure/azure-functions-host/issues/6805) since Azure Functions have their own authentication/authorization out of the box which conflicts with custom handlers etc, so I have wrote a library that handles it gracefully [https://www.nuget.org/packages/AzureFunctions.Authentication/](https://www.nuget.org/packages/AzureFunctions.Authentication/).

**Comment by artmasa** [comment]
@nazar-kuzo interesting findings in that issue. I will do deeper debugging in my library and see if there are any conflicts with built-in authentication. All the tests that I have done indicate Azure Functions Auth still works.
The new package version is available after merging #4

**Comment by nazar-kuzo** [comment]
@artmasa 

I assume that those lines breaks the out of the box authentication, since it removes their setup, I`m not sure about your test cases, but you can easily spot the difference when you instantiate and look into the contents of `AuthenticationSchemeProvider` and `AuthenticationHandlerProvider` when you dont call `builder.Services.AddAuthentication()` and when call it.

My first spot that something is wrong when you open Azure Portal and want to see a list of deployed functions, and stopped working for me whenever I call `builder.Services.AddAuthentication()`

**Comment by nazar-kuzo** [comment]
Without `builder.Services.AddAuthentication()`
![image](https://user-images.githubusercontent.com/13677730/142501338-5ec2cbab-2626-42fd-9b34-68a645daee18.png)

With `builder.Services.AddAuthentication()`
![image](https://user-images.githubusercontent.com/13677730/142501776-d939cb5a-9f68-472a-ad57-870c50826008.png)

If your tests ensue that those three schemes are present then you are golden 😉

**Comment by nazar-kuzo** [comment]
Ah, I see now what are you doing.

You are basically adding back function authorization based on this code:

https://github.com/dark-loop/functions-authorize/blob/3f4a28564f6a852cf2f131f85934c1393aaa70c7/src/DarkLoop.Azure.Functions.Authorize/Security/AuthenticationExtensions.cs#L51-L72

My library works in a different way, instead of recreating out of the box authorization it instantiates separate ServiceCollection with authentication/authorization info and injects it at runtime when extension is being bootstrapped

https://github.com/nazar-kuzo/azure-functions-authentication/blob/ca122402da95e6c492886110c6b7acd5e965c3db/src/AzureFunctions.Authentication/AzureFunctions.Authentication/FunctionAuthenticationExtensionConfigProvider.cs#L36-L56

**Comment by artmasa** [comment]
@nazar-kuzo I see I'm missing re-adding the `ArmToken` Auth back to the authentication methods. I will add that one and submit another pull request.
