### ISSUE TITLE
Missing built-in authentication schemes

### ISSUE THREAD

**Issue by artmasa** [dark-loop/functions-authorize#5]
Authentication schemes like `ArmToken` are missing in the authentication token as discussed in issue #3 with @nazar-kuzo

**Comment by artmasa** [comment]
Since I cannot find a way to reference host assemblies, it will be required to statically reference them to call the methods that setup built-in Azure Functions auth.

**Comment by nazar-kuzo** [comment]
Alternatively, you can do the same what I did:
- avoid calling .AddAuthentication on original service collection, but use newly created. This guarantees that original authentication schemes are in place.
- add an extension startup method which is called after, inject AuthenticationSchemeProvider and add new schemes dynamically, this approach is officially suggested on some Microsoft's forums.

This approach seems cleaner to me, since you dont produce the overhead at all and not touching a bit of existing authentication set up by host

**Comment by artmasa** [comment]
There's more logic to why built-in authN is not taking place. I can call `AddAuthentication` one hundred times with an instance of `IServiceCollection` and it's not going to ignore the configurations in the latest calls or different `AuthenticationBuilder` instances.
How do you track in your solution all the `JwtBearerOptions`, `OpenIdConnectOptions` or other scheme configurations that need to be passed to the handlers to execute auth as desired? The Options framework has multiple ways to define configuration that might be ignored when transferring them to the `IAuthenticationSchemeProvider`. Quite sure I might be missing something in your implementation that allows this. I'm referring to `IConfigureNamedOptions`, `IConfigureOptions`, `IValidateOptions`, `IPostConfigureOptions` , etc...

**Comment by nazar-kuzo** [comment]
@artmasa I totally understand you, but we are in the situation where both approaches are not ideal, so you still can decide your own way of doing it.

> How do you track in your solution all the JwtBearerOptions, OpenIdConnectOptions or other scheme configurations that need to be passed to the handlers to execute auth as desired?

Based on how `AddAuthentication` works, we can apply all configurations as is on existing `ServiceCollection` so I dont replicate them manually. Here is the extension:

https://github.com/nazar-kuzo/azure-functions-authentication/blob/ca122402da95e6c492886110c6b7acd5e965c3db/src/AzureFunctions.Authentication/AzureFunctions.Authentication/Extensions/FunctionAuthenticationExtensions.cs#L32-L54

Then I call the same configurations one already existing `SchemeProvider` and then copy all new schemes from isolated ServiceCollection.

https://github.com/nazar-kuzo/azure-functions-authentication/blob/ca122402da95e6c492886110c6b7acd5e965c3db/src/AzureFunctions.Authentication/AzureFunctions.Authentication/FunctionAuthenticationExtensionConfigProvider.cs#L36-L56

I will appreciate any example from your side that you might be worried about it is not working with my implementation. So I can debug it and tell you whether I can be handled or not.
For example I use such snippet and it works like a charm with bunch of configurations under the hood
![image](https://user-images.githubusercontent.com/13677730/143020336-66946712-37e8-4313-9900-d99e3c17ade5.png)

**Comment by artmasa** [comment]
@nazar-kuzo, where is the isolated `IServiceCollection` in your project. Maybe that is what I cannot still find and see how it relates to the schemes setup.
