### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by AkashDoke** [dark-loop/functions-authorize#54]
How can we validate AD access token with isolated function app

**Comment by artmasa** [comment]
@AkashDoke, you can add reference to `Microsoft.Identity.Web` and instead of calling `AddJwtFunctionsBearer` you can call any overload of `AddMicrosoftIdentityWebApi(...` which has been designed to work with Microsoft authentication providers (AAD, B2C, Live)
Also, make sure you don't use the default `Bearer` scheme. You can use `JwtFunctionsBearerDefaults.AuthenticationScheme` constant.

Please let me know

**Comment by artmasa** [comment]
Alternatively, you can use `AddOpenIdConnect(...` and configure it based on the values found in your Entra ID app registration

**Comment by AkashDoke** [comment]
Thank you for the response @artmasa 

I have below creds can you please help with how can i configure it for function app to do the access token based authentication ?

  "AzureAd": {
    "Authority": "https://login.microsoftonline.com/<<tenant-id>>",
    "ClientId": "<<CLIENTID>>",
    "ValidateAuthority": true
  }

**Comment by artmasa** [comment]
The magic on how aspnet core validates token is already built-in. If you look into the source you will notice that you just need set the `Authority` and `Audience` properties for a successful token validation.
The first assumption of the framework is that they are standards compliant. In you inspect the **headers** section of a token coming from AAD you will notice the `kid` and `x5t` elements. These are public key identifiers.
In order for the signature of a token to be verified you need access to these keys. When you implement your own token generation you have access to these keys within your application.

Microsoft authentication providers follow the OIDC standards. When you provide the value for the `Authority` property, for example `https://login.microsoftonline.com/<your-tenant>`, the framework will concatenate this value with the standard based metadata path: `/.well-known/openid-configuration`.

You can grab your authority value and append the string above: `https://login.microsoftonline.com/<your-tenant>/.well-known/openid-configuration` and paste it in your browser. You will receive a json payload with metadata. This json payload has the `jwks_uri`, also standard, with a URL to access the public keys used by the IdP to validate the signature on the tokens. One of these keys should match identifiers of the `kid` and `x5t` elements referenced above.

For ASPNET Core JWT Bearer auth, if you don't specify a custom `MetadataAddress` values and the URL referenced above is not resolved, or you don't provide a custom token validator; you would receive an error stating keys to validate signature were not found. Validating the signature is the default behavior for JWT Bearer handler.

So, the concept of validating authority is embedded in the process of validating the signature as the framework relies on the keys provided by the authority to validate the signature of your token.

All this functionality is available when you use the generic `AddJwtFunctionsBearer(...` method to configure your application. `AddMicrosoftIdentityWebApi(...` gives additional configuration for features only available on Microsoft identity providers, but all this is not required to validate the token (which validates the authority)

Conclusion: Just by providing the **Authority** property you are ensuring your application is verifying the received tokens come from such Authority.

I hope this explanation helps. Try the well known metadata address referenced above on your own and all these elements will start making sense pretty fast.

**Comment by artmasa** [comment]
The magic on how aspnet core validates token is already built-in. If you look into the source you will notice that you just need set the `Authority` and `Audience` properties for a successful token validation.
The first assumption of the framework is that they are standards compliant. In you inspect the **headers** section of a token coming from AAD you will notice the `kid` and `x5t` elements. These are public key identifiers.
In order for the signature of a token to be verified you need access to these keys. When you implement your own token generation you have access to these keys within your application.

Microsoft authentication providers follow the OIDC standards. When you provide the value for the `Authority` property, for example `https://login.microsoftonline.com/<your-tenant>`, the framework will concatenate this value with the standard based metadata path: `/.well-known/openid-configuration`.

You can grab your authority value and append the string above: `https://login.microsoftonline.com/<your-tenant>/.well-known/openid-configuration` and paste it in your browser. You will receive a json payload with metadata. This json payload has the `jwks_uri`, also standard, with a URL to access the public keys used by the IdP to validate the signature on the tokens. One of these keys should match identifiers of the `kid` and `x5t` elements referenced above.

For ASPNET Core JWT Bearer auth, if you don't specify a custom `MetadataAddress` value and the URL referenced above is not resolved, or you don't provide a custom token validator; you would receive an error stating keys to validate signature were not found. Validating the signature is the default behavior for JWT Bearer handler.

So, the concept of validating authority is embedded in the process of validating the signature as the framework relies on the keys provided by the authority to validate the signature of your token.

All this functionality is available when you use the generic `AddJwtFunctionsBearer(...` method to configure your application. `AddMicrosoftIdentityWebApi(...` gives additional configuration for features only available on Microsoft identity providers, but all this is not required to validate the token (which validates the authority)

Conclusion: Just by providing the **Authority** property you are ensuring your application is verifying the received tokens come from such Authority.

**Comment by AkashDoke** [comment]
![image](https://github.com/dark-loop/functions-authorize/assets/76030891/2e99e3dc-2200-43b5-aaab-021352eb2a07)


I am using above code still it is not working i am not really sure what went wrong. But your guidance here will be really helpful.

I am using functionV4 isolated mode.

**Comment by AkashDoke** [comment]
![image](https://github.com/dark-loop/functions-authorize/assets/76030891/a21bec15-3048-4bea-bd9b-80606c7662d0)

Getting this error

**Comment by artmasa** [comment]
First, you are leaving you `AddMicrosoftIdentityWebApi` with the default `Bearer` scheme. It needs to be changes to `FunctionsBearer` or any other custom scheme name.
Second the audience needs to match your token's `aud` claim. That might be the value it contains, just verify. Commonly the audience is in URI format and can be retrieved from the **Expose API** of your app registration in Entra ID as **API ID URI**

It should look like:
```csharp
services
    .AddFunctionsAuthentication(JwtFunctionsBearerDeafults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApi(
        options =>
        {
            options.Authority = "https://login.microsoftonline.com/<your-tenant-id>";
            options.Audience = "<the-aud-claim-in-a-token-for-api-you-know-comes-from-aad>";
        },
        JwtFunctionsBearerDefaults.AuthenticationScheme);
```

If you need to decode a token to extract the correct `aud` claim, use https://jwt.ms. It is ensured by this Microsoft site the token never leaves your browser.

**Comment by AkashDoke** [comment]
Thanks for the response @artmasa , i also tried above provided solutions but while working with azure c# function app getting below error, it will be really helpful if you can guide me on how can implement it in standard way ?

![image](https://github.com/dark-loop/functions-authorize/assets/76030891/ba451e45-78b8-4982-baaf-78395c4d6ffe)

**Comment by artmasa** [comment]
I guess for that method there's another function parameter that needs to be specified.
Try just using `AddJwtFunctionsBearer(options => { ... })` method, as what you are pursuing is signature validation with authority keys.

**Comment by AkashDoke** [comment]
![image](https://github.com/dark-loop/functions-authorize/assets/76030891/519b7931-95ef-4e68-b6c6-54a96d772b7e)


After implementing AddJwtFunctionsBearer getting above warnings :)

**Comment by artmasa** [comment]
You're on the right track! Now you know what key is being identified to validate the signature. Troubleshooting further at this point would requiring exposing your configuration (not advisable). You can send me a DM @artmasa at X with some way to connect. Would be glad to help.

**Comment by AkashDoke** [comment]
@artmasa  Was trying to ping you but getting warning as **cannot be messaged** 

Can you please assist it with what are the probable missing points that I may need to try to get it to work?

**Comment by artmasa** [comment]
@AkashDoke, sorry about that. I have changed my settings in X.
We need to look into why signature cannot ve verified with the provided key ID in the token. I don't think this is not related to the framework as we can see in the console, the aspnet framework is doing the expected to validate signature.

**Comment by artmasa** [comment]
Hi @AkashDoke, were you able to identify the problem with the token validation?

**Comment by AkashDoke** [comment]
Sorry @artmasa  I wont be able to fix the issue yet. Is there any chance so we can connect over any communication source and look into it together ? That will be really helpful

**Comment by AkashDoke** [comment]
Hey @artmasa  sorry to bother you, but its kind of urgent as we are going live in next 2days and we have to do this change on priority. Your help will be really appreciate.

**Comment by artmasa** [comment]
How can I contact you?

**Comment by AkashDoke** [comment]
@artmasa its kind of urgent we have last day today to get ready for PROD , you have some free time today connect that will be really helpful

**Comment by artmasa** [comment]
@AkashDoke, I have tried to reach you on Meet and Chat, but you don't seem to be available.

**Comment by AkashDoke** [comment]
Sorry @artmasa  i didn't receive any notification 

Can you please join here once you are available ?

To join the meeting on Google Meet, click this link: https://meet.google.com/xer-ysud-vew

Or open Meet and enter this code: xer-ysud-vew

**Comment by AkashDoke** [comment]
![image](https://github.com/dark-loop/functions-authorize/assets/76030891/a8c78684-c644-4967-91e5-fe82fb391cad)

@artmasa 

I have completed all the R&D task and function is working as expected still while using darkloop and authenticating function locally getting above error

**Comment by artmasa** [comment]
@AkashDoke it seems you have not configured the right audience in your function app. The token references a different value in the `aud` claim. You might want to compare these values

**Comment by artmasa** [comment]
@AkashDoke, Hope by now you have been able to solve the challenge. I will go ahead and close the issue.
